/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package practica1_simulador;

import java.util.Random;
import javax.swing.JOptionPane;

/**
 *
 * @author Alvaro
 */
public class Simulador extends javax.swing.JFrame {

    int turno,turnopasaje=1,totalavion=1;
    ListaDoble listaAviones = new ListaDoble();
    ColaSimple colaPasajeros = new ColaSimple();
    ListaSimple listaMantenimiento;
    ListaCircularDoble listaMaletas = new ListaCircularDoble();
    Maleta maleta = new Maleta();
    String info="";
    Pasajero pasajero = new Pasajero();
    Avion avion = new Avion();

    public Simulador() {
        initComponents();
        initComponents2();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtcantidad = new javax.swing.JTextField();
        txtestaciones = new javax.swing.JTextField();
        bttEmpezar = new javax.swing.JButton();
        bttSiguiente = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Consola = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Cantidad Aviones:");

        jLabel2.setText("Cantidad Estaciones:");

        bttEmpezar.setText("Empezar");
        bttEmpezar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttEmpezarActionPerformed(evt);
            }
        });

        bttSiguiente.setText("Siguiente");
        bttSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttSiguienteActionPerformed(evt);
            }
        });

        Consola.setBackground(new java.awt.Color(0, 0, 0));
        Consola.setColumns(20);
        Consola.setForeground(new java.awt.Color(255, 255, 255));
        Consola.setRows(5);
        jScrollPane1.setViewportView(Consola);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(txtcantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(txtestaciones)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(bttEmpezar)
                        .addGap(56, 56, 56)
                        .addComponent(bttSiguiente)))
                .addGap(62, 62, 62)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 491, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtcantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtestaciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(71, 71, 71)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bttEmpezar)
                    .addComponent(bttSiguiente))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 496, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bttEmpezarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttEmpezarActionPerformed
        empezar();

    }//GEN-LAST:event_bttEmpezarActionPerformed

    private void bttSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttSiguienteActionPerformed
        
    }//GEN-LAST:event_bttSiguienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Simulador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Simulador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Simulador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Simulador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Simulador().setVisible(true);
            }
        });
    }

    public void initComponents2() {
        setLayout(null);
        setLocationRelativeTo(null);

    }

    public void empezar() {
        setAviones(Integer.parseInt(txtcantidad.getText()));
        Airplane();
    }
    
    public void Airplane(){
        int indice = 0;
        while(indice != turno){
            int numeroAvion = avion.numeroAviones();
            listaAviones.agregarAlFinal(numeroAvion);
            colaPasajeros.encolar(pasajero.numeroPasajeros(numeroAvion));
            indice++;
        }
        maletas();
        System.out.println();
        colaPasajeros.imprimirCola();
        System.out.println();
        listaMaletas.imprimirListaCircular();
        mostrarAviones();
        mostrarPasajeros();
        Consola.append(info);
    }

    public void mostrarAviones(){
        Nodo auxiliar = new Nodo();
        auxiliar = colaPasajeros.listasimple.inicio;
        NodoDoble recorrer = new NodoDoble();
        recorrer = listaAviones.getInicio();
        Consola.append("********** Aviones ************"+"\n");
        while(recorrer != null){
            info += "Avion "+totalavion+"\n";
            totalavion++;
            int tipo = (int)recorrer.getDato();
            tipoAvion(tipo);
            info += "       Pasajeros: "+auxiliar.dato+"\n";
            desabordaje(tipo);
            mantenimiento(tipo);
            auxiliar = auxiliar.siguiente;
            recorrer = recorrer.getSiguiente();
        }
    }
    
    public void desabordaje(int tipo){
        switch(tipo){
            case 1:
                info+="      Desabordaje: 1"+"\n";
                break;
            case 2:
                info+="      Desabordaje: 2"+"\n";
                break;
            case 3:
                info+="      Desabordaje: 3"+"\n";
                break;
        }
    }
    
    public void tipoAvion(int tipo){
        switch (tipo) {
            case 1:
                info += "      Tipo: Pequenio" + "\n";
                break;
            case 2:
                info += "      Tipo: Mediano" + "\n";
                break;
            case 3:
                info += "      Tipo: Grande" + "\n";
                break;
        }
    }
    
    public void mantenimiento(int tipo){
        Random mantenimiento = new Random();
        int numeromant;
        switch(tipo){
            case 1:
                numeromant = mantenimiento.nextInt(3)+1;
                info += "      Mantenimiento: "+ numeromant + "\n";
                break;
            case 2:
                numeromant = mantenimiento.nextInt(2)+2;
                info += "      Mantenimiento: "+ numeromant + "\n";
                break;
            case 3:
                numeromant = mantenimiento.nextInt(3)+3;
                info += "      Mantenimiento: "+ numeromant + "\n";
                break;
        }
    }
    
    public void setAviones(int turno){
        this.turno = turno;
    }
    
    public int getAviones(){
        return turno;
    }
    
    public void maletas(){
        int dato;
        Nodo auxiliar = new Nodo();
        auxiliar = colaPasajeros.listasimple.inicio;
        while(auxiliar != null){
            dato = (int)auxiliar.dato;
            while(dato!=0){
                listaMaletas.agregarAlFinal(maleta.cantidadmaletas(dato));
                dato--;
            }
            auxiliar = auxiliar.siguiente;
        }
        listaAviones.imprimirListaCompleta();
    }
    
    public void mostrarPasajeros(){
        info+="********** Pasajeros ***********"+"\n";
        int dato;
        Nodo auxiliar = new Nodo();
        NodoCircular mal = new NodoCircular();
        mal = listaMaletas.primero;
        auxiliar = colaPasajeros.listasimple.inicio;
        while(auxiliar != null){
            dato = (int)auxiliar.dato;
            while(dato!=0){
                info+="Pasajero: "+turnopasaje+"\n";
                info+="        Documentos: "+pasajero.documentos(dato)+"\n";
                info+="        Maletas: "+mal.getDato()+"\n";
                mal = mal.siguiente;
                turnopasaje++;
                dato--;
            }
            auxiliar = auxiliar.siguiente;
        }
    }
    
    public ListaDoble getListaAviones() {
        return listaAviones;
    }

    public void setListaAviones(ListaDoble listaAviones) {
        this.listaAviones = listaAviones;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea Consola;
    private javax.swing.JButton bttEmpezar;
    private javax.swing.JButton bttSiguiente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtcantidad;
    private javax.swing.JTextField txtestaciones;
    // End of variables declaration//GEN-END:variables
}
